name: Go
on: [pull_request]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.15.x
        id: go
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1
      - name: CI Tasks
        run: make ci
      - name: Report
        uses: wolfeidau/coverage-report-action@v2
        with:
          github-token: ${{ secrets.github_token }}
          coverage-report: 'coverage.xml'
          minimum-coverage: 80
          show-files: true

